// Generated by CoffeeScript 1.9.3
(function() {
  var _max_N, _name_input_id, _ref_url, _usernum_to_colnum, init, login, resetChess, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  _ref_url = "https://smoveweb.firebaseio.com/";

  _name_input_id = "";

  _usernum_to_colnum = {
    0: 4,
    1: 4,
    2: 5,
    3: 6,
    4: 7,
    5: 7
  };

  _max_N = 4;


  /*
  	_UserList 	#idxxx :{name}
  				#idxxx :{name}
   	ChessRef	N --- 1..4
  				0:player
  				(...):
  				N^2-1:player
  		
  player =={0,name1,name2...}
   */

  init = function() {
    root.BaseRef = new Firebase(_ref_url);
    root.UserListRef = BaseRef.child('UserList');
    root.ChessRef = BaseRef.child('Chess');
    root.PlayerRef = UserListRef.push();
    PlayerRef.set({
      name: "",
      state: "online"
    });
    PlayerRef.onDisconnect().remove();
    root._UserList = void 0;
    root._Chess = void 0;
    root._Player = void 0;
    UserListRef.on('value', function(snapshot) {
      var n;
      root._UserList = [];
      snapshot.forEach(function(childSnapshot) {
        _UserList.push(childSnapshot.val());
        return false;
      });
      updateUserList();
      return n = _UserList.length;
    });
    ChessRef.on('value', function(snapshot) {
      root._Chess = snapshot.val();
      return updateChess();
    });
    PlayerRef.on('value', function(snapshot) {
      return root._Player = snapshot.val();
    });
    login();
    return resetChess(6);
  };

  login = function() {
    var LogDiv, nameField;
    $('canvas').hide();
    LogDiv = $('<div>').attr('id', 'loginDiv');
    LogDiv.append("<input type='text' id='nameInput' placeholder='enter a username...'>");
    $('body').append(LogDiv);
    nameField = $('#nameInput');
    nameField.focus();
    nameField.blur(function() {
      return nameField.focus();
    });
    return nameField.keypress(function(e) {
      var name;
      if (e.keyCode === 13) {
        name = nameField.val();
        setName(name);
        $(loginDiv).remove();
        $('#canvas').show();
        return game.run();
      }
    });
  };

  resetChess = function(cols) {
    var i, m, ref1, results, x, y;
    ChessRef.set({
      cols: cols
    });
    results = [];
    for (x = i = 0, ref1 = cols - 1; 0 <= ref1 ? i <= ref1 : i >= ref1; x = 0 <= ref1 ? ++i : --i) {
      results.push((function() {
        var j, ref2, results1;
        results1 = [];
        for (y = j = 0, ref2 = cols - 1; 0 <= ref2 ? j <= ref2 : j >= ref2; y = 0 <= ref2 ? ++j : --j) {
          m = x + y * cols;
          results1.push(ChessRef.child(m).set(0));
        }
        return results1;
      })());
    }
    return results;
  };

  window.updateUserList = function() {};

  window.updateChess = function() {};

  window.setName = function(name) {
    if (name === "" || name === void 0) {
      console.error('failed to set name');
      return false;
    } else {
      PlayerRef.update({
        name: name
      });
      return true;
    }
  };

  window.getUserList = function() {
    return _UserList;
  };

  window.getChess = function() {
    return _Chess;
  };

  window.getPlayer = function() {
    return _Player;
  };

  window.getUserRefByName = function(name) {
    return UserListRef.on('value', function(snapshot) {
      var ref;
      ref = null;
      return snapshot.forEach(childSnapshot)(function() {
        if (childSnapshot.name === name) {
          return childSnapshot.ref();
        } else {
          return false;
        }
      });
    });
  };

  window.ChessPosition = function(x, y, set) {
    var n;
    n = x + (_Chess.cols * y);
    if (set === void 0) {
      return _Chess[n];
    } else {
      n = x + (_Chess.cols * y);
      return ChessRef.child(n).set(set);
    }
  };

  window.PlayerState = function(s) {
    if (s === void 0) {
      return CurrentState;
    } else {
      return PlayerRef.update({
        state: s
      });
    }
  };

  init();

}).call(this);
